---

# (c) Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: purge /var/lib/postgresql/data
  shell: |
    set -o pipefail
    find /var/lib/postgresql/data -mindepth 1 -delete
  args:
    executable: "/bin/bash"
    removes: "/var/lib/postgresql/data/PG_VERSION"
  register: result
  changed_when: result is not succeeded

- name: prepare directories
  file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
    state: "{{ item.state | default('directory') }}"
  loop:
    - { dest: "/docker-entrypoint-initdb.d" }
    - { dest: "/usr/share/postgresql/{{ postgres_release }}" }
    - { dest: "/var/lib/postgresql", owner: "postgres", group: "postgres" }
    - { dest: "/var/lib/postgresql/data", owner: "postgres", group: "postgres" }
    - { dest: "/var/run/postgresql", owner: "postgres", group: "postgres" }

- name: "prepare /usr/share/postgresql/postgresql.conf.sample"
  shell: |
    set -o pipefail
    mv /usr/share/postgresql/{{ postgres_release }}/postgresql.conf.sample /usr/share/postgresql/
    ln -s ../postgresql.conf.sample /usr/share/postgresql/{{ postgres_release }}/postgresql.conf.sample
  args:
    executable: "/bin/bash"
    creates: "/usr/share/postgresql/postgresql.conf.sample"
  register: result
  until: result is succeeded
  changed_when: result is not succeeded

- name: copy templates
  template:
    dest: "{{ item.dest }}"
    src: "{{ item.src | default('./templates' + item.dest + '.j2') }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  loop:
    - { dest: "/usr/share/postgresql/postgresql.conf.sample" }

- name: prepare files
  file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
    state: "{{ item.state | default('file') }}"
  loop:
    - { dest: "/usr/share/postgresql/postgresql.conf.sample" }

- name: flush cache
  shell: |
    set -o pipefail
    rm -rf /var/lib/apt/lists/*
  args:
    executable: "/bin/bash"
  changed_when: false
  ignore_errors: true
